# Generated by Django 2.0.10 on 2021-04-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20210417_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='remaining_invitation',
            new_name='remaining_invitations',
        ),
    ]
